# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-06 11:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0008_auto_20160606_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='head_img',
            field=models.ImageField(blank=True, null=True, upload_to='uploads', verbose_name='头像'),
        ),
    ]
