# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-21 06:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_author_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('published', '已出版'), ('producing', '待出版'), ('forbidden', '进出')], default='producing', max_length=32),
        ),
    ]
