# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-22 10:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0004_userprofile_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='Wechat_num',
            field=models.IntegerField(default=11111, max_length=12),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='head_img',
            field=models.ImageField(blank=True, null=True, upload_to='uploads', verbose_name='头像'),
        ),
    ]
