# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-23 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0005_auto_20160622_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='Wechat_num',
            field=models.IntegerField(),
        ),
    ]
