# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-03 07:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': '课程', 'verbose_name_plural': '课程'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': '客户', 'verbose_name_plural': '客户'},
        ),
        migrations.AlterModelOptions(
            name='school',
            options={'permissions': (('view_task', 'Cak See available tasks'),), 'verbose_name': '学校', 'verbose_name_plural': '学校'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': '用户', 'verbose_name_plural': '用户'},
        ),
        migrations.AlterField(
            model_name='classlist',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Course', verbose_name='课程'),
        ),
        migrations.AlterField(
            model_name='consultrecord',
            name='note',
            field=models.TextField(verbose_name='跟进内容'),
        ),
        migrations.AlterField(
            model_name='studyrecord',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='日期'),
        ),
    ]
